[package]
name = "sample"
version = "0.1.0"
authors = ["Andra Antariksa <andra.antariksa@gmail.com>"]
edition = "2018"

[[bin]]
name = "sample"
path = "src/main.rs"

[lib]
name = "sample"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[workspace]
members = ["crates/*"]

[dependencies]
helix-core = { version = "0.1.0", path = "crates/helix-core" }

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { version = "0.3.0", features = ["logger"] }
